default: &default
  coffee_time:
    active: false
    channel: rotating-coffee-time
    schedule: weekly
    size: 2
  q_branch:
    active: false
    channel: rotating-q-branch
    schedule: weekly
    size: 2
  rotating_brunch:
    active: true
    channel: rotating-brunch
    schedule: fortnightly
    size: 4

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
